title: Trials And Tribulations Of Parenting In The 21st Century
author: Terry Murphy
email: terryjmurphy71@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog discussing parenting challenges, specifically, those relating to managing the online activities of our children
  and putting in place the infrastructure required to keep them safe from others (and themselves).

# social links
# twitter_username: your-twitter-handle
github_username:  terry-sydaus

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
